trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create, name="create"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('daily_tasks/', views.select_day, name='daily_tasks'),
    path('charge/<int:customer_id>', views.confirm, name='charge'),
    path('select_day/<str:day_of_the_week>', views.select_day, name ='select_day')
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding Django's built in routes (login and logout). Notice there is no 'login' function in accounts/views.py. Django takes care of this for us.
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate trach_collector/views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/employees/models.py
from django.db import models

class Employee(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    address = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=5)
 
    def __str__(self):
        return self.name

# TODO: Create an Employee model with properties required by the user stories

trash_collector/employees/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.apps import apps
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from datetime import date, datetime
import calendar
from django.db.models import Q
from .models import Employee

@login_required
def index(request):
    # This line will get the Customer model from the other app, it can now be used to query the db for Customers
    Customer = apps.get_model('customers.Customer')
    logged_in_employee = request.user
    try:
        logged_in_employee = Employee.objects.get(user=logged_in_employee)
        today = date.today()
        day_of_week = calendar.day_name[today.weekday()]
        pickups_by_zip = Customer.objects.filter(zip_code = logged_in_employee.zip_code) #This grabs all the customers with the employees zipcode
        pickups_by_pickup_date = pickups_by_zip.filter(weekly_pickup = day_of_week) | pickups_by_zip.filter(one_time_pickup = today) #This is where we determine if today is the pickup day or extra pickup 
        pickups_non_suspend = pickups_by_pickup_date.exclude(suspend_start__lt = today, suspend_end__gt = today) #This exclues all suspended accounts
        #confirm sets last pick up.

        context = {
            'logged_in_employee': logged_in_employee,
            'today': today,
            'pickups_by_zip': pickups_by_zip,
            'pickups_by_pickup_date':pickups_by_pickup_date,
            'pickups_non_suspend': pickups_non_suspend 
        }

        return render(request, 'employees/index.html', context)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('employees:create'))

@login_required
def create(request):
    logged_in_user = request.user
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        address_from_form = request.POST.get('address')
        zip_from_form = request.POST.get('zip_code')
        new_employee = Employee(name=name_from_form, user=logged_in_user, zip_code=zip_from_form)
        new_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/create.html')  


def edit_profile(request):
    logged_in_user = request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        zip_from_form = request.POST.get('zip_code')
        logged_in_employee.name = name_from_form
        logged_in_employee.zip_code = zip_from_form
        logged_in_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        context = {
            'logged_in_employee': logged_in_employee
        }
        return render(request, 'employees/edit_profile.html', context)


def confirm(request, customer_id):
    try:
        Customers = apps.get_model('customers.Customer')
        charge_customer = Customers.objects.get(id =customer_id)
        charge_customer.balance += 20
        charge_customer.date_of_last_pickup = datetime.now()
        charge_customer.save()
        
        return render(request, 'employees/index.html')
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('employees:index'))

# def select_day(request):
#     user = request.user
#     logged_in_employee = Employee.objects.get(user=user)
#     Customers = apps.get_model('customers.Customer')
#     pickup_customers = Customers.objects.all()
#     current_day = str(date.today())
#     weekday = request.POST.get('day_of_the_week')
    

#     context = { 
#                 'pickup_customers': pickup_customers,
#                 'weekday': weekday
#     }
#     if request.method == 'POST':
#         return HttpResponseRedirect(reverse('employees:index'))
#     return render(request, 'employees/daily_tasks.html', context)



def select_day(request, day_of_the_week):
    user = request.user
    logged_in_employee = Employee.objects.get(user=user)
    Customers = apps.get_model('customers. Customer')
    if request.method == "POST":
        pickup_customers = Customers.objects.filter(weekly_pickup = day_of_the_week)

        weekday = request.POST.get('day _of_the week')
        context = {
                    'pickup_ customers' : pickup_customers,
                    'weekday' : weekday
        }
        return render (request, 'employees/daily_tasks.html', context)

trash_collector/employees/templates/employees/create.html
{% extends 'base.html' %}

{% block title %} Employee Create {% endblock %}

{% block header %} Please Complete Registration {% endblock %}

{% block content %}

<form action="{% url 'employees:create' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name"><br />
    Address: <input type="text" name="address" id="address"><br />
    Zip Code: <input type="text" name="zip_code" id="zip_code"><br />
    <input type="submit" value="Register">
</form>

{% endblock %}

trash_collector/employees/templates/employees/daily_tasks.html
{% extends 'employees/employee_base.html' %}

{% block title %} Employee Daily Tasks {% endblock %}
{% block header %} <h1>Daily Tasks</h1> {% endblock %}

{% block content %}
<br>
<form action="{% url 'employees:daily_tasks' %}" name="charge_customer" id="charge_customer">
    {% csrf_token %}
<div class="container" style="text-align: center">
        <div class="row">
            <div div class="col-md">
                <h5 style="text-align: center;">Customers on Your Pickup Route Today</h5>
                <hr>
                <div class="filter" style="text-align: right">
                    <form action="{% url 'employees:daily_tasks' %}">
                        {% csrf_token %}
                        <form action = "{% url 'employees:select_day' day_of_the_week %}" name = 'daily_tasks' id= 'daily_tasks'>
                            <select name = "day_of_the_week" id = "day_of_the_week">
                            <option value = 'Monday' selected = "Monday">Monday</option>
                            <option value = 'Tuesday' selected = "Tuesday">Tuesday</option>
                            <option value = 'Wednesday' selected = "Wednesday">Wednesday</option>
                            <option value = 'Thursday' selected = "Thursday">Thursday</option>
                            <option value = 'Friday' selected = "Friday">Friday</option>
                        </select>
                        <input type = "submit" value = "Submit"> 
                    </form>
                </form>
                </div>
                <div class="card card-body">
                    <table class="table table-sm">
                        <thead class="thead-dark">
                        <tr>
                            <th>Name</th>
                            <th>Steet Address</th>
                            <th>Zip Code</th>
                            <th>Weekly Pickup Date</th>
                            <th>Balance</th>
                            <th>Confirm Pickup</th>
                        </tr>
                        <tbody>
                            {% for customer in pickup_customers %}
                        <tr>
                            <td>{{ customer.name }}</td>
                            <td>{{ customer.address }}</td>
                            <td>{{ customer.zip_code }}</td>
                            <td>{{ customer.weekly_pickup}}</td>
                            <td>${{ customer.balance }}</td>
                            <td><a href="{% url 'employees:charge' customer.id %}">Confirm Trash Pick Up</a></td>
                        </tr>
                        {% endfor %}
                        </tbody> 
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

trash_collector/employees/templates/employees/daily_view.html
{% extends 'employees/employee_base.html' %}

{% block title %} Employee Daily View {% endblock %}
{% block header %} <h1>Employee Daily View</h1> {% endblock %}

{% block content %}
<br>
<form action="{% url 'employees:daily_view'  %}" name="charge_customer" id="charge_customer" method='POST'>
    {% csrf_token %}
<div class="container" style="text-align: center">
        <div class="row">
            <div div class="col-md">
                <h5 style="text-align: center;">Customers on Your Pickup Route Today</h5>
                <hr>
                <div class="filter" style="text-align: right">
                    <form action="{% url 'employees:daily_view' %}" method='POST'>
                        {% csrf_token %}
                        <form action = "{% url 'employees:daily_view'%}" name = 'daily_view' id= 'daily_view' method = 'POST'>
                         <select name = "day_of_the_week" id = "day_of_the_week">
                            <option value = 'Monday' selected = "Monday">Monday</option>
                            <option value = 'Tuesday' selected = "Tuesday">Tuesday</option>
                            <option value = 'Wednesday' selected = "Wednesday">Wednesday</option>
                            <option value = 'Thursday' selected = "Thursday">Thursday</option>
                            <option value = 'Friday' selected = "Friday">Friday</option>
                        </select>
                        <input type = "submit" value = "Submit"> 
                    </form>
                </form>
                </div>
                <div class="card card-body">
                    <table class="table table-sm">
                        <thead class="thead-dark">
                        <tr>
                            <th>Name</th>
                            <th>Steet Address</th>
                            <th>Zip Code</th>
                            <th>Weekly Pickup Date</th>
                            <th>Balance</th>
                            <th>Confirm Pickup</th>
                        </tr>
                        <tbody>
                            {% for customer in pickup_customers %}
                        <tr>
                            <td>{{ customer.name }}</td>
                            <td>{{ customer.address }}</td>
                            <td>{{ customer.zip_code }}</td>
                            <td>{{ customer.weekly_pickup}}</td>
                            <td>${{ customer.current_balance }}</td>
                            <td><input type = 'submit' value='Confirm'></td>
                        </tr>
                        {% endfor %}
                        </tbody> 
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

trash_collector/employees/templates/employees/edit_profile.html
{% extends 'employees/employee_base.html' %}

{% block title %} Employee Profile Edit {% endblock %}

{% block header %} Update Your Information {% endblock %}

{% block content %}
<br />
<form action="{% url 'employees:edit_profile' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name" value="{{logged_in_employee.name}}">
    <br />
    <br />
    Zip Code: <input type="text" name="zip_code" id="zip_code" value="{{logged_in_employee.zip_code}}">
    <br />
    <input type="submit" value="Submit">
</form>

{% endblock %}

trash_collector/employees/templates/employees/employee_base.html
{% extends 'base.html' %}

{% block navbar %}
    <a class="nav-item nav-link" href="{% url 'employees:index' %}">Home</a>
    <a class="nav-item nav-link" href="{% url 'employees:edit_profile' %}">Edit Profile</a>
    <a class="nav-link" href="{% url 'employees:daily_tasks' %}">Daily Tasks</a>
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'employees/employee_base.html' %}

{% block title %} Employee Home {% endblock %}

{% block header %} Employee Portal {% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello Employee {{ user.username }}!<br />
    Address: {{ logged_in_employee.address }} {{ logged_in_employee.zip_code }}<br />
    <br />
    <br />
    Customers Zip Code:
    <ul>
      <l1>
       {% for customer in pickups_by_zip %}
       {{ customer.name }} {{ customer.zip_code }}
       <br>                                                            
       {% endfor %}
      </l1>
    </ul>                                                            
    Todays Trash Pickups: 
    <ul>
      <l1>
        {% for customer in pickups_non_suspend %}
         Name: {{ customer.name }} has a weekly pick up on {{ customer.weekly_pickup }}
         <br>
         {% endfor %}<a href="{% url 'employees:daily_tasks' %}">Confirm Pickup</a>
      </l1>
    </ul>
    
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}